### ISSUE TITLE
Immediate publish causes token error

### ISSUE THREAD

**Issue by wejendorp** [Tradeshift/io#15]
**Describe the bug**
When following the example from the readme, the `hub` responds with a token error and ignores the message.

**To Reproduce**
Code or link to code to reproduce the behavior:

```js
const app = ts.io();
app.publish('some-target', 'some-topic', 'data');
```

**Expected behavior**
Expect hub to receive message `{target: 'some-target'}`, but instead `io` logs an error that token is not valid.

**Comment by sampi** [comment]
fix has been released
