### ISSUE TITLE
Hub tries to ping itself and times out

### ISSUE THREAD

**Issue by wejendorp** [Tradeshift/io#16]
**Describe the bug**
When initializing a new `hub`, the frame tries to ping itself.

**To Reproduce**
Code or link to code to reproduce the behavior:
```js
const hub = ts.io({
	appIdByWindow: win => {

	},
	windowByAppId: (appId, sourceWindow) => {

	},
	appTimeout() {
		console.log('Timed out');
	}
});
```

Resulting console output:
```
> Source and destination match, discarding message!
{
  "type": "PONG",
  "token": "c8ceb2d7-88a3-44de-bd25-dec076688b3f",
  "viaHub": true
}
> Source and destination match, discarding message!
{
  "type": "PONG",
  "token": "c8ceb2d7-88a3-44de-bd25-dec076688b3f",
  "viaHub": true
}
> Timed out
```

**Expected behavior**
"nothing", i.e. no events should be passed, since no frames have connected to the hub.

**Comment by sampi** [comment]
the hub will throw some error messages if it's initialized like this, it needs some basic things returned by default, otherwise this will happen.
